import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const akRasmee = localFont({
   src: "../public/fonts/AK Rasmee/AK Rasmee.ttf",
   variable: "--font-ak-rasmee",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="dv" dir="rtl">
         <body className={`${akRasmee.className}  antialiased dark`}>
            {children}
         </body>
      </html>
   );
}
